// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGaOPNcOzHsqdsVVwVdq8MWo2pjHt7I4A',
    appId: '1:1075448064421:web:548cb087a285a7bb7f604c',
    messagingSenderId: '1075448064421',
    projectId: 'chatapp-20e78',
    authDomain: 'chatapp-20e78.firebaseapp.com',
    storageBucket: 'chatapp-20e78.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDw4panjs0opyHD-bSfs6iX44Pcq6XnaME',
    appId: '1:1075448064421:android:ecaf77a89ae8d7667f604c',
    messagingSenderId: '1075448064421',
    projectId: 'chatapp-20e78',
    storageBucket: 'chatapp-20e78.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAv6xsg186K6dYzhB3rL195daYin2WPmw',
    appId: '1:1075448064421:ios:572057f9a14058357f604c',
    messagingSenderId: '1075448064421',
    projectId: 'chatapp-20e78',
    storageBucket: 'chatapp-20e78.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAv6xsg186K6dYzhB3rL195daYin2WPmw',
    appId: '1:1075448064421:ios:572057f9a14058357f604c',
    messagingSenderId: '1075448064421',
    projectId: 'chatapp-20e78',
    storageBucket: 'chatapp-20e78.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGaOPNcOzHsqdsVVwVdq8MWo2pjHt7I4A',
    appId: '1:1075448064421:web:c6d7b430908e876f7f604c',
    messagingSenderId: '1075448064421',
    projectId: 'chatapp-20e78',
    authDomain: 'chatapp-20e78.firebaseapp.com',
    storageBucket: 'chatapp-20e78.firebasestorage.app',
  );
}
